module.exports = Object.freeze({
    BALANCE_OPERATION_WITHDRAW: 'WITHDRAW',
    BALANCE_OPERATION_DEPOSIT: 'DEPOSIT',
    BALANCE_OPERATION_EXCHANGE: 'EXCHANGE',
    BALANCE_CURRENCY_USD: 'USD',
    ROLE_ADMIN: 'admin',
    ROLE_USER: 'user'
});
