name: Deploy Workflow

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: [self-hosted, linux, marketplace-partners-api]  # This specifies that the job should run on a self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to Production
        run: pwd 
      - name: Check path
        run: pwd
      - name: Check node version
        run: node -v
      - name: Copy env
        run: printf "ENV=production\nAPP_ENV=production\nP4U_CATEGORIES_TASK_ID=b4216c6c-ec37-4e76-94cb-2f6ff76aebbf\nP4U_TITLE_TASK_ID=640c1677-89c1-44f8-84f0-0033047dbfca\nP4U_DESCRIPTION_TASK_ID=120825f0-c26f-41d9-bbe8-e59771fa8aca\nP4U_CLIENT_AI_KEY=\nAPP_PORT=3030\nMONGO_DB_AUTO_INDEX=false\nMONGO_DB_DEBUG=false\nHTTP_API_DEBUG=false\nROLLBAR_TOKEN=\nLOGTAIL_TOKEN=\nAPI_ACCESS_TOKEN=\nMONGO_DB_CONNECTION=mongodb+srv://\nMONGO_DB_REPLICATION_CONNECTION=mongodb+srv://\nMONGO_DB_API_DATABASE_CONNECTION=mongodb+srv://\nS3_ACCESS_KEY_ID=\nS3_SECRET_ACCESS_KEY=\nS3_BUCKET_NAME=\nS3_REGION=\nS3_ENDPOINT=https://\nS3_BACKUP_MARKER_START=\nS3_BACKUP_KEY_LIST=10\nS3_BACKUP_MONGO_BUCKET=\nREFERRAL_COMMISSION_AMOUNT=10\nCHROMIUM_PATH=''\nCIPHER_KEY=\nSEO_CONTENT_MIN_CHARS=500\nSEO_INDEXING_REPORT=false\nREDIS_USERNAME=\nREDIS_SECRET=\nREDIS_DATABASE=\nREDIS_HOST=\nREDIS_PORT=\nREDIS_DEFAULT_EXPIRE=300\nIMAGE_HOST_CDN=https://\nFINGERPRINT=\nSALT_FOR_BCRYPT=10\nOPEN_EXCHANGE_RATES_APP_ID=" >> .env
      - name: Start install package
        run: yarn
      - name: Stop all services
        run: yarn pm2 stop all | yarn pm2 delete all | yarn pm2 save --force
      # - name: Start all job service
        # run: yarn pm2 start "yarn jobs:start"
      # - name: Start main app
        # run: yarn pm2 start "yarn app"
      - name: Start main server
        run: yarn pm2 start "yarn server"
      - name: Save pm
        run: yarn pm2 save
